### PR TITLE
Add support for Python 3.12

### PR DESCRIPTION
**Pull request by bartosz-rippling**
Update workflows to support Python 3.12

### CODE REVIEW

**Comment by bartosz-rippling** [comment]
@aviramha Could you please verify if this change is sufficient to provide support for Python 3.12?

**Comment by aviramha** [comment]
Thanks for sending this. Can you remove the Python 3.7 part as well please?

**Comment by bartosz-rippling** [comment]
@aviramha Python 3.7 removed, could you please review it?

**Comment by aviramha** [comment]
CI fails :(

**Review by aviramha — APPROVED** [review]

**Pull request merged**
